"use client";

import { useEffect, useState } from "react";

const API = "http://127.0.0.1:8765";
type Proposal = { proposal_id: string; content: string; provenance: string; sensitivity: string; status: string };
type PlatformAction = { action_id: string; platform: string; target_id: string; text: string; status: string };

export default function OperatorClient() {
  const [health, setHealth] = useState("Checking…"); const [version, setVersion] = useState(""); const [approval, setApproval] = useState("No response queued.");
  const [me, setMe] = useState("{}"); const [meStatus, setMeStatus] = useState(""); const [output, setOutput] = useState(""); const [responseEvidence, setResponseEvidence] = useState("No grounded response evidence loaded.");
  const [proposals, setProposals] = useState<Proposal[]>([]); const [platformEvents, setPlatformEvents] = useState<unknown[]>([]); const [actions, setActions] = useState<PlatformAction[]>([]); const [status, setStatus] = useState("");
  const [pendingCorrelationId, setPendingCorrelationId] = useState<string | null>(null);

  async function loadStatus() { try { const [h, v] = await Promise.all([fetch(`${API}/health`), fetch(`${API}/version`)]); setHealth(`Orchestrator: ${(await h.json()).status}`); setVersion(`Version: ${(await v.json()).version}`); } catch { setHealth("Orchestrator: offline"); } }
  async function loadMe() { try { const response = await fetch(`${API}/me`); setMe(JSON.stringify(await response.json(), null, 2)); setMeStatus("Loaded"); } catch (error) { setMeStatus(`Error: ${String(error)}`); } }
  async function loadProposals() { try { const data = await (await fetch(`${API}/memory/proposals`)).json() as { proposals: Proposal[] }; setProposals(data.proposals.filter((item) => item.status === "pending")); } catch { setProposals([]); } }
  async function loadPlatforms() { try { const [events, actionData] = await Promise.all([fetch(`${API}/platforms/events`), fetch(`${API}/platforms/actions`)]); setPlatformEvents((await events.json()).events ?? []); setActions(((await actionData.json()).actions ?? []).filter((item: PlatformAction) => item.status === "proposed")); } catch { setPlatformEvents([]); setActions([]); } }
  useEffect(() => { void loadStatus(); void loadMe(); void loadProposals(); void loadPlatforms(); }, []);

  async function mockResponse() { const data = await (await fetch(`${API}/dev/mock-response`, { method: "POST" })).json(); setApproval(data.event.payload.requires_operator_approval ? "Approval required" : "Approved for mock local display"); setOutput(JSON.stringify(data.event.payload, null, 2)); }
  async function observeRespond() { const data = await (await fetch(`${API}/dev/observe-and-respond`, { method: "POST" })).json(); const correlationId = typeof data.metadata?.correlation_id === "string" ? data.metadata.correlation_id : null; setPendingCorrelationId(correlationId); setResponseEvidence(JSON.stringify({ correlation_id: correlationId, response: data.response, citations: data.metadata?.citations }, null, 2)); setOutput(JSON.stringify(data.response, null, 2)); setApproval(correlationId ? "Approval required before public output" : "No response queued"); }
  async function approveResponse() { if (!pendingCorrelationId) return; const response = await fetch(`${API}/dev/approve-response`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ correlation_id: pendingCorrelationId }) }); const data = await response.json(); setApproval(response.ok ? "Approved and published" : String(data.error ?? "Approval failed")); setOutput(JSON.stringify(data.response ?? data, null, 2)); setPendingCorrelationId(null); }
  async function saveMe() { try { const response = await fetch(`${API}/me`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: me }); if (!response.ok) throw new Error(await response.text()); setMeStatus("Saved for this orchestrator session"); } catch (error) { setMeStatus(`Error: ${String(error)}`); } }
  async function proposalAction(path: string, proposal: Proposal, content?: string) { await fetch(`${API}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ proposal_id: proposal.proposal_id, ...(content === undefined ? {} : { content }) }) }); await loadProposals(); }
  async function action(path: string, item: PlatformAction, text?: string) { await fetch(`${API}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action_id: item.action_id, ...(text === undefined ? {} : { text }) }) }); await loadPlatforms(); }
  async function suggest() { const newest = platformEvents.at(-1) as { event_id?: string } | undefined; if (!newest?.event_id) { setStatus("No platform event is available"); return; } const response = await fetch(`${API}/platforms/actions/suggest`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event_id: newest.event_id, language: "en" }) }); setStatus(response.ok ? "Reply suggestion queued for approval" : await response.text()); await loadPlatforms(); }
  async function evidence() { await fetch(`${API}/dev/mock-observation`, { method: "POST" }); const [e, o] = await Promise.all([fetch(`${API}/evidence`), fetch(`${API}/observations`)]); setOutput(JSON.stringify({ evidence: await e.json(), observations: await o.json() }, null, 2)); }

  return <main className="web-route operator-page"><nav className="site-nav"><a className="brand" href="/chat">SIDURI</a><div><a href="/chat">Chat</a><a className="active" href="/operator">Console</a></div></nav><p className="eyebrow">SIDURI / OPERATOR</p><h1>Foundation console</h1><p className="muted">Private local controls. Nothing here posts to a public platform.</p>
    <div className="grid"><article><h2>Service</h2><p>{health}</p><p>{version}</p></article><article><h2>Response gate</h2><p>{approval}</p><button onClick={() => void mockResponse()}>Trigger mock response</button> <button className="secondary" onClick={() => void observeRespond()}>Observe and respond</button> <button className="secondary" disabled={!pendingCorrelationId} onClick={() => void approveResponse()}>Approve grounded response</button></article></div>
    <section className="editor"><h2>Me knowledge</h2><p className="muted">Local editable profile. Keep private facts out of stream-safe fields.</p><textarea value={me} onChange={(event) => setMe(event.target.value)} spellCheck={false} aria-label="Me knowledge JSON" /><div><button className="secondary" onClick={() => void loadMe()}>Reload</button> <button onClick={() => void saveMe()}>Save profile</button><span id="me-status">{meStatus}</span></div></section>
    <section className="editor"><h2>Memory candidates</h2><p className="muted">Candidates stay isolated until reviewed.</p>{proposals.length ? proposals.map((item) => <ProposalCard key={item.proposal_id} item={item} onAction={proposalAction} />) : <p>No pending candidates.</p>}<button className="secondary" onClick={() => void loadProposals()}>Refresh candidates</button></section>
    <section className="evidence"><h2>Evidence inspection</h2><p className="muted">Bounded citations and synthetic observations.</p><button className="secondary" onClick={() => void evidence()}>Create fixture observation</button><pre>{output || "No evidence loaded."}</pre></section>
    <section className="editor"><h2>Platform inbox</h2><p className="muted">Public text is untrusted and remains operator-only.</p><button className="secondary" onClick={() => void loadPlatforms()}>Refresh platform events</button> <button className="secondary" onClick={() => void suggest()}>Suggest reply for newest event</button><span id="platform-status">{status}</span><pre>{JSON.stringify(platformEvents, null, 2)}</pre><h3>Outbound suggestions</h3>{actions.length ? actions.map((item) => <ActionCard key={item.action_id} item={item} onAction={action} />) : <p>No outbound actions.</p>}</section><pre>{responseEvidence}</pre>
  </main>;
}

function ProposalCard({ item, onAction }: { item: Proposal; onAction: (path: string, item: Proposal, content?: string) => Promise<void> }) { const [content, setContent] = useState(item.content); return <div className="proposal"><div className="proposal-meta">{item.provenance} · {item.sensitivity} · {item.proposal_id}</div><textarea value={content} onChange={(event) => setContent(event.target.value)} aria-label={`Memory candidate ${item.proposal_id}`} /><button className="secondary" onClick={() => void onAction("/memory/proposals/update", item, content)}>Save edit</button> <button onClick={() => void onAction("/memory/proposals/approve", item)}>Approve</button> <button className="secondary" onClick={() => void onAction("/memory/proposals/reject", item)}>Reject</button></div>; }
function ActionCard({ item, onAction }: { item: PlatformAction; onAction: (path: string, item: PlatformAction, text?: string) => Promise<void> }) { const [text, setText] = useState(item.text); return <div className="proposal"><div className="proposal-meta">{item.platform} · {item.target_id} · {item.action_id}</div><textarea value={text} onChange={(event) => setText(event.target.value)} aria-label={`Platform action ${item.action_id}`} /><button onClick={() => void onAction("/platforms/actions/approve", item, text)}>Approve</button> <button className="secondary" onClick={() => void onAction("/platforms/actions/reject", item)}>Reject</button></div>; }
